In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('diabeties.csv')

In [3]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
data.shape

(768, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
data.duplicated().sum()

0

In [11]:
X = data.drop('Outcome', axis=1)
y = data.Outcome

In [12]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = .20,random_state=42 )

C:\Users\Administrator\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [13]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
log_reg.coef_

array([[ 0.06618011,  0.03381642, -0.01381982,  0.00455788, -0.00192357,
         0.10139588,  0.59420902,  0.03628394]])

In [15]:
y_pred = log_reg.predict(X_train)

In [16]:
pd.DataFrame({'y_tain':y_train, 'y_pred':y_pred})

     y_tain  y_pred
60        0       0
618       1       0
346       0       0
294       0       1
231       1       1
..      ...     ...
71        0       0
106       0       0
270       1       1
435       1       1
102       0       0

[614 rows x 2 columns]

In [17]:
correct = 0
for y,yp in zip(y_train,y_pred):
    if y == yp:
        correct+=1
        
correct

473

In [18]:
correct/614

0.7703583061889251

In [20]:
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [21]:
confusion_matrix(y_train,y_pred)

array([[354,  47],
       [ 94, 119]], dtype=int64)

In [22]:
accuracy_score(y_train,y_pred)

0.7703583061889251

In [23]:
precision_score(y_train,y_pred)

0.7168674698795181

In [24]:
recall_score(y_train,y_pred)

0.5586854460093896

In [25]:
f1_score(y_train,y_pred)

0.6279683377308708

In [27]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       401
           1       0.72      0.56      0.63       213

    accuracy                           0.77       614
   macro avg       0.75      0.72      0.73       614
weighted avg       0.76      0.77      0.76       614